module.exports = {
  rootDir: '.',
  testEnvironment: 'node',
  verbose: true,
  resetModules: true,
  clearMocks: true,
  silent: true,
  testMatch: ['**/src/**/*.test.js'],
  reporters: ['default', ['github-actions', { silent: false }], 'summary'],
  collectCoverageFrom: ['src/**/*.js'],
  coveragePathIgnorePatterns: [
    '<rootDir>/node_modules/',
    '<rootDir>/postman/',
    '<rootDir>/.server',
    '<rootDir>/src/__fixtures__',
    "src/helpers/db/data",
    "src/helpers/secure-context",
    "src/helpers/proxy-agent.js",
    "src/helpers/proxy-fetch.js",
    "src/api/data",
    "src/helpers/db/mocks",
    "src/index",
    "src/config",
    "src/helpers/db"    ],
  coverageDirectory: '<rootDir>/coverage'
}
